In [1]:
import pandas as pd
from itertools import combinations

from src.utils import get_data_directory
from src.submissions import generate_matchups

In [2]:
YEAR = 2024

#### Load Team Data

In [3]:
df_teams_men = pd.read_csv(get_data_directory() / "MTeams.csv")
df_teams_women = pd.read_csv(get_data_directory() / "WTeams.csv")

In [4]:
df_teams_men.head()

   TeamID     TeamName  FirstD1Season  LastD1Season
0    1101  Abilene Chr           2014          2025
1    1102    Air Force           1985          2025
2    1103        Akron           1985          2025
3    1104      Alabama           1985          2025
4    1105  Alabama A&M           2000          2025

In [5]:
df_teams_women.head()

   TeamID     TeamName
0    3101  Abilene Chr
1    3102    Air Force
2    3103        Akron
3    3104      Alabama
4    3105  Alabama A&M

In [6]:
# Only keep teams that are in D1 for the given year
df_teams_men = df_teams_men[(df_teams_men['FirstD1Season'] <= YEAR) & (df_teams_men['LastD1Season'] >= YEAR)]

# drop unused columns
df_teams_men = df_teams_men[['TeamID',]]
df_teams_women = df_teams_women[['TeamID',]]
df_teams_men.head()

   TeamID
0    1101
1    1102
2    1103
3    1104
4    1105

In [7]:
def create_matchup_df(df_teams):
    return pd.DataFrame(
        [(min(a, b), max(a, b)) for a, b in combinations(df_teams['TeamID'], 2)],
        columns=['lowerID', 'higherID']
    )

In [8]:
df_matchups_men = create_matchup_df(df_teams_men)
df_matchups_women = create_matchup_df(df_teams_women)

In [9]:
df_matchups_men.tail()

       lowerID  higherID
65336     1475      1477
65337     1475      1478
65338     1476      1477
65339     1476      1478
65340     1477      1478

In [10]:
df_matchups_women.tail()

       lowerID  higherID
71248     3477      3479
71249     3477      3480
71250     3478      3479
71251     3478      3480
71252     3479      3480

In [11]:
df_matchups = pd.concat((df_matchups_men, df_matchups_women)).reset_index(drop=True)

In [12]:
df_matchups.head()

   lowerID  higherID
0     1101      1102
1     1101      1103
2     1101      1104
3     1101      1105
4     1101      1106

In [13]:
# add new column 'ID' in the format 'YEAR_lowerID_higherID'
df_matchups['ID'] = df_matchups.apply(lambda row: f"{YEAR}_{row['lowerID']}_{row['higherID']}", axis=1)

In [14]:
df_matchups.head()

   lowerID  higherID              ID
0     1101      1102  2024_1101_1102
1     1101      1103  2024_1101_1103
2     1101      1104  2024_1101_1104
3     1101      1105  2024_1101_1105
4     1101      1106  2024_1101_1106

#### Test Library Function

In [15]:
df_matchups = generate_matchups(YEAR)

In [16]:
df_matchups

        lowerID  higherID              ID
0          1101      1102  2024_1101_1102
1          1101      1103  2024_1101_1103
2          1101      1104  2024_1101_1104
3          1101      1105  2024_1101_1105
4          1101      1106  2024_1101_1106
...         ...       ...             ...
136589     3477      3479  2024_3477_3479
136590     3477      3480  2024_3477_3480
136591     3478      3479  2024_3478_3479
136592     3478      3480  2024_3478_3480
136593     3479      3480  2024_3479_3480

[136594 rows x 3 columns]