In [1]:
import pandas as pd
from itertools import combinations

from src.utils import get_data_directory
from src.submissions import generate_matchups

In [2]:
YEAR = 2025

#### Load Team Data

In [3]:
df_teams_men = pd.read_csv(get_data_directory() / "MRegularSeasonCompactResults.csv")
df_teams_women = pd.read_csv(get_data_directory() / "WRegularSeasonCompactResults.csv")

In [4]:
df_teams_men.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1985      20     1228      81     1328      64    N      0
1    1985      25     1106      77     1354      70    H      0
2    1985      25     1112      63     1223      56    H      0
3    1985      25     1165      70     1432      54    H      0
4    1985      25     1192      86     1447      74    H      0

In [5]:
df_teams_women.head()

   Season  DayNum  WTeamID  WScore  LTeamID  LScore WLoc  NumOT
0    1998      18     3104      91     3202      41    H      0
1    1998      18     3163      87     3221      76    H      0
2    1998      18     3222      66     3261      59    H      0
3    1998      18     3307      69     3365      62    H      0
4    1998      18     3349     115     3411      35    H      0

In [6]:
# Only keep teams that are in D1 for the given year
df_teams_men = df_teams_men[df_teams_men["Season"] == YEAR]
df_teams_women = df_teams_women[df_teams_women["Season"] == YEAR]

# collect all team ids that appear in either WTeamID or LTeamID, sort them ascending and drop duplicates
df_teams_men = pd.DataFrame({"TeamID": sorted(pd.unique(df_teams_men[["WTeamID", "LTeamID"]].values.ravel()))})
df_teams_women = pd.DataFrame({"TeamID": sorted(pd.unique(df_teams_women[["WTeamID", "LTeamID"]].values.ravel()))})

df_teams_men.head()

   TeamID
0    1101
1    1102
2    1103
3    1104
4    1105

In [7]:
len(df_teams_women)

362

In [8]:
len(df_teams_men)

364

In [9]:
def create_matchup_df(df):
    return pd.DataFrame(
        [(min(a, b), max(a, b)) for a, b in combinations(df["TeamID"], 2)], columns=["lowerID", "higherID"]
    )

In [10]:
df_matchups_men = create_matchup_df(df_teams_men)
df_matchups_women = create_matchup_df(df_teams_women)

In [11]:
df_matchups_men.tail()

       lowerID  higherID
66061     1477      1479
66062     1477      1480
66063     1478      1479
66064     1478      1480
66065     1479      1480

In [12]:
df_matchups_women.tail()

       lowerID  higherID
65336     3477      3479
65337     3477      3480
65338     3478      3479
65339     3478      3480
65340     3479      3480

In [13]:
df_matchups = pd.concat((df_matchups_men, df_matchups_women)).reset_index(drop=True)

In [14]:
df_matchups.head()

   lowerID  higherID
0     1101      1102
1     1101      1103
2     1101      1104
3     1101      1105
4     1101      1106

In [15]:
# add new column 'ID' in the format 'YEAR_lowerID_higherID'
df_matchups["ID"] = df_matchups.apply(lambda row: f"{YEAR}_{row['lowerID']}_{row['higherID']}", axis=1)

In [16]:
df_matchups.head(10)

   lowerID  higherID              ID
0     1101      1102  2025_1101_1102
1     1101      1103  2025_1101_1103
2     1101      1104  2025_1101_1104
3     1101      1105  2025_1101_1105
4     1101      1106  2025_1101_1106
5     1101      1107  2025_1101_1107
6     1101      1108  2025_1101_1108
7     1101      1110  2025_1101_1110
8     1101      1111  2025_1101_1111
9     1101      1112  2025_1101_1112

In [17]:
len(df_matchups)

131407

#### Test Library Function

In [18]:
df_matchups = generate_matchups(YEAR)

In [19]:
df_matchups

        lowerID  higherID              ID
0          1101      1102  2025_1101_1102
1          1101      1103  2025_1101_1103
2          1101      1104  2025_1101_1104
3          1101      1105  2025_1101_1105
4          1101      1106  2025_1101_1106
...         ...       ...             ...
131402     3477      3479  2025_3477_3479
131403     3477      3480  2025_3477_3480
131404     3478      3479  2025_3478_3479
131405     3478      3480  2025_3478_3480
131406     3479      3480  2025_3479_3480

[131407 rows x 3 columns]